# Generated by Django 5.1.2 on 2024-10-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('Post', models.CharField(blank=True, max_length=30, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('Post', models.CharField(blank=True, max_length=30, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Reply', models.CharField(blank=True, max_length=300, null=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('Workdescription', models.CharField(blank=True, max_length=300, null=True)),
                ('Status', models.CharField(blank=True, max_length=300, null=True)),
                ('Assigndate', models.DateTimeField(blank=True, null=True)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
                ('STAFF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stafftable')),
            ],
        ),
    ]
